import os
import tempfile
import random
import string
from dotenv import load_dotenv
from google.adk.agents import Agent
from google.adk.models import Gemini
from google.adk.tools import ToolContext
from pptx import Presentation
from google.genai import types
from google.cloud import storage

load_dotenv()

model_name = os.environ.get("MODEL_NAME")

async def generate_powerpoint_deck(
    slides: list[dict],
    filename: str = "RFP_Response_Deck.pptx",
    tool_context: ToolContext = None,
) -> str:
    """Generates a professional PowerPoint presentation (.pptx) deck based on the RFP response and uploads it to GCS.

    Args:
        slides: A list of slide dictionaries. Each dictionary must contain:
          - 'title': The slide title string.
          - 'subtitle': Optional (for the cover slide) subtitle string.
          - 'bullets': A list of strings representing bullet points.
          - 'notes': Optional speaker notes string.
        filename: The name of the PowerPoint file to save (e.g., "H&R_Block_RFP_Response_Deck.pptx").

    Returns:
        A success message with the GCS URI of the generated PowerPoint presentation.
    """
    try:
        base, ext = os.path.splitext(filename)
        postfix = "".join(random.choices(string.ascii_lowercase + string.digits, k=4))
        unique_filename = f"{base}_{postfix}{ext}"
        
        prs = Presentation()
        
        # 1. Title/Cover Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        first_slide = slides[0] if slides else {}
        title.text = first_slide.get("title", "RFP Response Proposal")
        subtitle.text = first_slide.get("subtitle", "Generated by GALE AI Agent")
        
        # 2. Body Slides
        bullet_slide_layout = prs.slide_layouts[1]
        body_slides = slides[1:] if len(slides) > 1 else []
        
        for slide_data in body_slides:
            slide = prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = slide_data.get("title", "Slide Title")
            
            tf = body_shape.text_frame
            bullets = slide_data.get("bullets", [])
            if bullets:
                tf.text = bullets[0]
                for bullet in bullets[1:]:
                    p = tf.add_paragraph()
                    p.text = bullet
                    p.level = 0
                    
            notes = slide_data.get("notes", "")
            if notes:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                text_frame.text = notes
        
        # Save to temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pptx") as tmp:
            output_path = tmp.name
        prs.save(output_path)
        
        # Upload to GCS
        try:
            bucket_name = os.environ.get("GCS_PPTX_BUCKET", "ninghai-bucket-0")
            pptx_path = os.environ.get("GCS_PPTX_PATH", "pptx")
            
            gcs_client = storage.Client()
            bucket = gcs_client.bucket(bucket_name)
            blob = bucket.blob(f"{pptx_path}/{unique_filename}")
            blob.upload_from_filename(output_path)
            gcs_uri = f"gs://{bucket_name}/{pptx_path}/{unique_filename}"
        except Exception as gcs_err:
            gcs_uri = f"Failed GCS upload: {gcs_err}"
        
        # Save as ADK session artifact
        if tool_context:
            with open(output_path, "rb") as f:
                pptx_bytes = f.read()
            part = types.Part.from_bytes(
                data=pptx_bytes,
                mime_type="application/vnd.openxmlformats-officedocument.presentationml.presentation"
            )
            await tool_context.save_artifact(filename=unique_filename, artifact=part)
            
        # Clean up temporary file
        try:
            os.remove(output_path)
        except Exception:
            pass
            
        return f"Successfully generated PowerPoint deck. GCS Link: {gcs_uri}"
    except Exception as e:
        return f"Failed to generate PowerPoint presentation: {e}"


PROMPT_PATH = os.path.join(os.path.dirname(__file__), "../prompts/ppt_agent_instruction.md")
with open(PROMPT_PATH, "r", encoding="utf-8") as f:
    ppt_instruction = f.read()

ppt_agent = Agent(
    name="ppt_agent",
    model=Gemini(
        model=model_name,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    description="Generates a beautiful PowerPoint presentation deck based on the final RFP response.",
    instruction=ppt_instruction,
    tools=[generate_powerpoint_deck],
    output_key="ppt_agent_output"
)
